--------------------------------------------------------------------------------
--
-- $Id:$
--
-- linz_asp_uploader -  LINZ ASP loader for PostgreSQL
--
-- Copyright 2012 Crown copyright (c)
-- Land Information New Zealand and the New Zealand Government.
-- All rights reserved
--
-- This program is released under the terms of the new BSD license. See the 
-- LICENSE file for more information.
--
--------------------------------------------------------------------------------
SET client_min_messages TO WARNING;

DO $SCHEMA$
BEGIN

IF EXISTS (SELECT * FROM pg_namespace where LOWER(nspname) = 'asp') THEN
    RETURN;
END IF;

CREATE SCHEMA asp AUTHORIZATION bde_dba;

GRANT ALL ON SCHEMA asp TO bde_dba;
GRANT USAGE ON SCHEMA asp TO bde_admin;
GRANT USAGE ON SCHEMA asp TO bde_user;

SET search_path = asp, public;

CREATE TABLE CHECK_COMBINATION(
	COMBINATION	VARCHAR(11)	NOT NULL PRIMARY KEY,
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);

CREATE TABLE GED_CODES(
	CODE	VARCHAR(3)	NOT NULL  PRIMARY KEY,
	NAME	VARCHAR(30)	NOT NULL,
	ABBREVIATION	VARCHAR(18)	NULL,
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);

CREATE TABLE MAP_10000(
	MAP_ID	VARCHAR(3)	NOT NULL  PRIMARY KEY,
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);


CREATE TABLE MAP_260(
	MAP_ID	VARCHAR(3)	NOT NULL  PRIMARY KEY,
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);

CREATE TABLE MED_CODES(
	CODE	VARCHAR(2)	NOT NULL PRIMARY KEY,
	NAME	VARCHAR(30)	NOT NULL,
	ABBREVIATION	VARCHAR(18)	NULL, 
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);

CREATE TABLE NAME_ASSOCIATIONS(
	ID	INT		NOT NULL  PRIMARY KEY,
	NAME_1_SUFI	BIGINT	NOT NULL, 
	NAME_2_SUFI	BIGINT	NOT NULL, 
	ALIAS	CHAR(1)	NULL, 
	STATUS	CHAR(1)	NOT NULL, 
	MODIFIED	TIMESTAMP	NOT NULL
);

CREATE TABLE PLACE(
	ID	INT		NOT NULL  PRIMARY KEY,
	SUFI	BIGINT	NOT NULL, 
	NAME	VARCHAR(52)	NOT NULL, 
	LOCALITY	VARCHAR(30)	NOT NULL, 
	CREATED	TIMESTAMP	NOT NULL,
	MODIFIED	TIMESTAMP	NOT NULL, 
	TEXT	VARCHAR(240)	NULL,
	UNOFFICIAL_FLAG	CHAR(1)	NULL,
	EDITOR	VARCHAR(8)	NOT NULL,
	STATUS	CHAR(1)	NULL,
	VERSION	INT	NULL,
	EDIT_ACTION	CHAR(1)	NULL 
);

CREATE TABLE PLACE_PART(
	ID	INT		NOT NULL  PRIMARY KEY,
	SUFI	BIGINT	NOT NULL, 
	PLACE_SUFI	BIGINT	NOT NULL, 
	MAP_260	VARCHAR(3)	NULL,
	MAP_10000	VARCHAR(3)	NULL, 
	GED	VARCHAR(3)	NOT NULL,
	MED	VARCHAR(2)	NOT NULL,
	TLA	VARCHAR(3)	NOT NULL,
	TEXT	VARCHAR(240)	NULL, 
	MODIFIED	TIMESTAMP	NOT NULL, 
	EDITOR	VARCHAR(8)	NOT NULL,
	STATUS	CHAR(1)	NULL,
	CREATED	TIMESTAMP	NULL, 
	VERSION	INT	NULL,
	EDIT_ACTION	CHAR(1)	NULL 
);

CREATE TABLE PROCESSING_CENTRES(
	CODE	SMALLINT	NOT NULL  PRIMARY KEY, 
	NAME	VARCHAR(30)	NOT NULL, 
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);

CREATE TABLE STATUS_TYPES(
	STATUS	CHAR(1)	NOT NULL  PRIMARY KEY,
	NAME	VARCHAR(20)	NOT NULL, 
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);

CREATE TABLE STREET(
	ID	INT		NOT NULL  PRIMARY KEY,
	SUFI	BIGINT	NOT NULL, 
	NAME	VARCHAR(52)	NOT NULL, 
	LOCALITY	VARCHAR(30)	NOT NULL, 
	CREATED	TIMESTAMP	NOT NULL,
	MODIFIED	TIMESTAMP	NOT NULL, 
	TEXT	VARCHAR(240)	NULL,
	UNOFFICIAL_FLAG	CHAR(1)	NULL,
	EDITOR	VARCHAR(8),
	VERSION	INT	NULL,
	EDIT_ACTION	CHAR(1)	NULL,
	STATUS	CHAR(1)	NULL
);

CREATE TABLE STREET_PART(
	ID	INT		NOT NULL  PRIMARY KEY, 
	SUFI	BIGINT	NOT NULL, 
	STREET_SUFI	BIGINT	NOT NULL, 
	MAP_260	VARCHAR(3)	NULL,
	MAP_10000	VARCHAR(3)	NULL, 
	ODD_RANGE	VARCHAR(15)	NULL,
	EVEN_RANGE	VARCHAR(15)	NULL,
	GED	VARCHAR(3)	NOT NULL,
	MED	VARCHAR(2)	NOT NULL,
	TLA	VARCHAR(3)	NOT NULL,
	TEXT	VARCHAR(240)	NULL, 
	MODIFIED	TIMESTAMP	NOT NULL, 
	EDITOR	VARCHAR(8)	NOT NULL,
	CREATED	TIMESTAMP	NULL,
	VERSION	INT	NULL,
	EDIT_ACTION	CHAR(1)	NULL,
	STATUS	CHAR(1)	NULL
);

CREATE TABLE STREET_TYPE(
	STD_ABB	VARCHAR(4)	NOT NULL  PRIMARY KEY, 
	FULL_NAME	VARCHAR(40)	NOT NULL,
	ASP_ABB	VARCHAR(12)	NULL,
	SNZ_ABB	VARCHAR(2)	NULL,
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);

CREATE TABLE TLA_CODES(
	CODE	VARCHAR(3)	NOT NULL PRIMARY KEY,
	NAME	VARCHAR(30)	NOT NULL,
	PROCESSING_CENTRE	SMALLINT	NOT NULL, 
	ABBREVIATION	VARCHAR(18)	NULL, 
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);

CREATE TABLE UNOFFICIAL_STATUS(
	CODE	CHAR(1)	NOT NULL PRIMARY KEY, 
	NAME	VARCHAR(20)	NOT NULL,
	MODIFIED	TIMESTAMP	NOT NULL,
	ID          SERIAL NOT NULL,
    UNIQUE (ID)
);

END;
$SCHEMA$;
